
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


import sys
import tkinter as tk
from pathlib import Path
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Button, PhotoImage, ttk, messagebox
from tkcalendar import DateEntry
from default_entry import DefaultTextEntry
from storage import school_data_1 as sd1, school_data_2 as sd2, school_data_3 as sd3
from sql_connection import connection_database

def education_main():
    # Get the script's directory path
    SCRIPT_DIR = Path(sys.argv[0]).resolve().parent

    # Set the relative path to the assets directory
    ASSETS_PATH = SCRIPT_DIR / "assets" / "apply_frame3"

    def relative_to_assets(path: str) -> Path:
        return ASSETS_PATH / Path(path)


    def add_more_clicked():
        confirmation_message = "Are you sure you want to add more entries?"

        if sd1.cur_educ_list >= 3:
            # If the limit of 3 inputs is reached, show an error message box
            messagebox.showerror("Input Limit Exceeded", "You have reached the maximum limit of inputs (3).")
      
        else:
            # Show the confirmation messagebox
            confirm = messagebox.askquestion("Confirmation", confirmation_message)
            if confirm == 'yes':
                if education_attainment_var.get() == "Junior High School":
                    education_attainment_var.set("JHS")
                elif education_attainment_var.get() == "Senior High School":
                    education_attainment_var.set("SHS")
                elif education_attainment_var.get() == "College":
                    education_attainment_var.set("CO")

                school_name = school_name_var.get()
                school_address = school_address_entry.get()
                date_graduated = date_graduated_entry.get_date()
                education_attainment = education_attainment_var.get()

                if school_name == d_school_name_entry or school_address == d_school_address_entry or date_graduated == "" or education_attainment == "Select Education Attainment":
                    messagebox.showerror("Error", "Please fill out all fields.")
                else:
                    if sd1.cur_educ_list == 1:
                        sd1.school_name = school_name
                        sd1.school_address = school_address
                        sd1.date_graduated = date_graduated
                        sd1.educ_attainment = education_attainment

                        school_name_var.set("Select your school")
                        school_address_entry.delete(0, "end")
                        date_graduated_entry.delete(0, "end")
                        education_attainment_var.set("Select Education Attainment")

                        # For Debugging Purposes
                        # print(sd1.school_name)
                        # print(sd1.school_address)
                        # print(sd1.date_graduated)
                        # print(sd1.educ_attainment)
                    elif sd1.cur_educ_list == 2:
                        sd2.school_name = school_name
                        sd2.school_address = school_address
                        sd2.date_graduated = date_graduated
                        sd2.educ_attainment = education_attainment

                        school_name_var.set("Select your school")
                        school_address_entry.delete(0, "end")
                        date_graduated_entry.delete(0, "end")
                        education_attainment_var.set("Select Education Attainment")

                        # For Debugging Purposes
                        # print(sd2.school_name)
                        # print(sd2.school_address)
                        # print(sd2.date_graduated)
                        # print(sd2.educ_attainment)
                    # elif sd1.cur_educ_list == 3:
                    #     sd3.school_name = school_name
                    #     sd3.school_address = school_address
                    #     sd3.date_graduated = date_graduated
                    #     sd3.educ_attainment = education_attainment

                        # school_name_entry.delete(0, "end")
                        # school_address_entry.delete(0, "end")
                        # date_graduated_entry.delete(0, "end")
                        # education_attainment_var.set("Select Education Attainment")

                        # For Debugging Purposes
                        # print(sd3.school_name)
                        # print(sd3.school_address)
                        # print(sd3.date_graduated)
                        # print(sd3.educ_attainment)

                        
                        
                    # Increment the counter only if the data is successfully added
                    sd1.cur_educ_list += 1

                    # Reset the entry boxes and education_attainment_var
            else:
                # Do nothing, the user clicked 'no'
                pass


    def back_clicked():
        school_name = school_name_var.get()
        school_address = school_address_entry.get()
        date_graduated = date_graduated_entry.get_date()
        education_attainment = education_attainment_var.get()
        if sd1.cur_educ_list == 1:
            sd1.school_name = school_name
            sd1.school_address = school_address
            sd1.date_graduated = date_graduated
            sd1.educ_attainment = education_attainment

            # For Debugging Purposes
            # print(sd1.school_name)
            # print(sd1.school_address)
            # print(sd1.date_graduated)
            # print(sd1.educ_attainment)
        elif sd1.cur_educ_list == 2:
            sd2.school_name = school_name
            sd2.school_address = school_address
            sd2.date_graduated = date_graduated
            sd2.educ_attainment = education_attainment

            # For Debugging Purposes
            # print(sd2.school_name)
            # print(sd2.school_address)
            # print(sd2.date_graduated)
            # print(sd2.educ_attainment)
        elif sd1.cur_educ_list == 3:
            sd3.school_name = school_name
            sd3.school_address = school_address
            sd3.date_graduated = date_graduated
            sd3.educ_attainment = education_attainment

            # For Debugging Purposes
            # print(sd3.school_name)
            # print(sd3.school_address)
            # print(sd3.date_graduated)
            # print(sd3.educ_attainment)

        window.destroy()
        from __3_apply_employment import employment_main
        employment_main()
    
    def next_clicked():
        if education_attainment_var.get() == "Junior High School":
            education_attainment_var.set("JHS")
        elif education_attainment_var.get() == "Senior High School":
            education_attainment_var.set("SHS")
        elif education_attainment_var.get() == "College":
            education_attainment_var.set("CO")

        school_name = school_name_var.get()
        school_address = school_address_entry.get()
        date_graduated = date_graduated_entry.get_date()
        education_attainment = education_attainment_var.get()

        if school_name == d_school_name_entry or school_address == d_school_address_entry or date_graduated == "" or education_attainment == "Select Education Attainment":
            messagebox.showerror("Error", "Please fill out all fields.")
        else:
            
            if sd1.cur_educ_list == 1:
                sd1.school_name = school_name
                sd1.school_address = school_address
                sd1.date_graduated = date_graduated
                sd1.educ_attainment = education_attainment

            elif sd1.cur_educ_list == 2:
                sd1.school_name = school_name
                sd1.school_address = school_address
                sd1.date_graduated = date_graduated
                sd1.educ_attainment = education_attainment
                
            elif sd1.cur_educ_list == 3:
                sd3.school_name = school_name
                sd3.school_address = school_address
                sd3.date_graduated = date_graduated
                sd3.educ_attainment = education_attainment

                # For Debugging Purposes
                print(sd1.school_name)
                print(sd1.school_address)
                print(sd1.date_graduated)
                print(sd1.educ_attainment)

                print(sd2.school_name)
                print(sd2.school_address)
                print(sd2.date_graduated)
                print(sd2.educ_attainment)

                print(sd3.school_name)
                print(sd3.school_address)
                print(sd3.date_graduated)
                print(sd3.educ_attainment)

            # connection_database()
            window.destroy()
            from __5_apply_work_exp import work_experience_main
            work_experience_main()



    def display_values():
        if sd1.cur_educ_list == 1:  # Check if there are any entries in the list
            # School Name
            if sd1.school_name == d_school_name_entry:
                pass
            elif sd1.school_name != "":
                school_name_var.set(sd1.school_name)

            # School Address
            if sd1.school_address == d_school_address_entry:
                pass
            elif sd1.school_address != "":
                school_address_entry.delete(0, tk.END)
                school_address_entry.insert(0, sd1.school_address)
                school_address_entry.config(fg="black")

            # Date Graduated
            if sd1.date_graduated != "":
                date_graduated_entry.set_date(sd1.date_graduated)

            if sd1.educ_attainment != "":
                education_attainment_var.set(sd1.educ_attainment)
        if sd1.cur_educ_list == 2:
            # School Name
            if sd2.school_name == d_school_name_entry:
                pass
            elif sd2.school_name != "":
                school_name_var.set(sd2.school_name)

            # School Address
            if sd2.school_address == d_school_address_entry:
                pass
            elif sd2.school_address != "":
                school_address_entry.delete(0, tk.END)
                school_address_entry.insert(0, sd2.school_address)
                school_address_entry.config(fg="black")

            # Date Graduated
            if sd2.date_graduated != "":
                date_graduated_entry.set_date(sd2.date_graduated)

            # Educational Attainment
            if sd2.educ_attainment != "":
                education_attainment_var.set(sd2.educ_attainment)
        if sd1.cur_educ_list == 3:
            # School Name
            if sd3.school_name == d_school_name_entry:
                pass
            elif sd3.school_name != "":
                school_name_var.set(sd3.school_name)

            # School Address
            if sd3.school_address == d_school_address_entry:
                pass
            elif sd3.school_address != "":
                school_address_entry.delete(0, tk.END)
                school_address_entry.insert(0, sd3.school_address)
                school_address_entry.config(fg="black")

            # Date Graduated
            if sd3.date_graduated != "":
                date_graduated_entry.set_date(sd3.date_graduated)

            # Educational Attainment
            if sd3.educ_attainment != "":
                education_attainment_var.set(sd3.educ_attainment)

    # Function to update the school address entry
    def update_school_address(event):
        selected_school = school_name_var.get()
        school_address_entry.delete(0, tk.END)
        school_address_entry.insert(0, school_addresses.get(selected_school, "Address not available"))

    d_school_name_entry = "Select your school"
    d_school_address_entry = "Enter School Address"
    window = Tk()

    # --------------------------------------------------------------------------------#
    # ---------------------------------- GUI SETUP ---------------------------------- #
    # --------------------------------------------------------------------------------#
    
    window.geometry("1024x568")
    window.configure(bg = "#CCD4D9")
    fontstyle = "Montserrat"

    canvas = Canvas(
        window,
        bg = "#CCD4D9",
        height = 568,
        width = 1024,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        512.0,
        23.0,
        image=image_image_1
    )

    image_image_2 = PhotoImage(
        file=relative_to_assets("image_2.png"))
    image_2 = canvas.create_image(
        880.0,
        147.0,
        image=image_image_2
    )

    image_image_3 = PhotoImage(
        file=relative_to_assets("image_3.png"))
    image_3 = canvas.create_image(
        710.0,
        147.0,
        image=image_image_3
    )

    image_image_4 = PhotoImage(
        file=relative_to_assets("image_4.png"))
    image_4 = canvas.create_image(
        553.0,
        147.0,
        image=image_image_4
    )

    image_image_5 = PhotoImage(
        file=relative_to_assets("image_5.png"))
    image_5 = canvas.create_image(
        386.0,
        147.0,
        image=image_image_5
    )

    image_image_6 = PhotoImage(
        file=relative_to_assets("image_6.png"))
    image_6 = canvas.create_image(
        176.0,
        147.0,
        image=image_image_6
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        696.0,
        261.0,
        image=entry_image_1
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        696.0,
        347.0,
        image=entry_image_2
    )

    entry_image_3 = PhotoImage(
        file=relative_to_assets("entry_3.png"))
    entry_bg_3 = canvas.create_image(
        327.0,
        261.0,
        image=entry_image_3
    )

    entry_image_4 = PhotoImage(
        file=relative_to_assets("entry_4.png"))
    entry_bg_4 = canvas.create_image(
        327.0,
        347.0,
        image=entry_image_4
    )

    image_image_7 = PhotoImage(
        file=relative_to_assets("image_7.png"))
    image_7 = canvas.create_image(
        200.0,
        231.0,
        image=image_image_7
    )

    image_image_8 = PhotoImage(
        file=relative_to_assets("image_8.png"))
    image_8 = canvas.create_image(
        200.0,
        317.0,
        image=image_image_8
    )

    image_image_9 = PhotoImage(
        file=relative_to_assets("image_9.png"))
    image_9 = canvas.create_image(
        567.0,
        231.0,
        image=image_image_9
    )

    image_image_10 = PhotoImage(
        file=relative_to_assets("image_10.png"))
    image_10 = canvas.create_image(
        587.0,
        317.0,
        image=image_image_10
    )

    image_image_11 = PhotoImage(
        file=relative_to_assets("image_11.png"))
    image_11 = canvas.create_image(
        511.0,
        78.0,
        image=image_image_11
    )

    # --------------------------------------------------------------------------------#
    # --------------------------------- ENTRY SETUP --------------------------------- #
    # --------------------------------------------------------------------------------#
                            # "Ateneo de Manila University",
                           
                            # "Far Eastern University",
                            # "Polytechnic University of the Philippines",
                            # "Polytechnic University of the Philippines-San Juan",
                            # "Polytechnic University of the Philippines-Parañaque",
                            # "Polytechnic University of the Philippines-Taguig",
                            # "Philippines Science High School",
                            # "University of the East",
                            # "Japan-Philippines Institue of Technology Plaridel Campus Inc.",
                            # "Technological Institute of the Philippines",
                            # "University of the Philippines-Diliman",
                            # "University of the Philippines-Manila",
                            # "University of the Philippines-Los Banos",
    # Name of School
    # Source: https://counselorcorporation.com/list-of-universities-in-philippines/
    school_name_options = [ 
                            "Abe International Business College",
                            "Abra State Institute of Science and Technology",
                            "ACLC College of Butuan",
                            "ACTS Computer College Sta Cruz",
                            "Adamson University",
                            "Adventist International Institute of Advanced Studies",
                            "Adventist University of the Philippines",
                            "Agusan Del Sur College",
                            "Aklan State University",
                            "Aldersgate College",
                            "Alliance Graduate School",
                            "AMA Computer College Tuguegarao",
                            "AMA Computer University",
                            "Angeles University Foundation",
                            "Araullo University",
                            "Arellano University",
                            "Asia Pacific College",
                            "Asian College of Technology",
                            "Asian Institute of Journalism and Communication",
                            "Asian Institute of Management",
                            "Asian Institute of Maritime Studies",
                            "Asian Social Institute Manila",
                            "Asian Theological Seminary Philippines",
                            "Ateneo de Davao University",
                            "Ateneo de Manila University",
                            "Ateneo de Naga University",
                            "Ateneo de Zamboanga University",
                            "Aurora State College of Technology",
                            "Bagui Central University",
                            "Baguio College of Technology",
                            "Basilan State College",
                            "Bataan Peninsula State University",
                            "Batanes State College",
                            "Batangas State University",
                            "Benedicto College",
                            "Benguet State University",
                            "Bestlink College of the Philippines",
                            "Bicol Christian College of Medicine AMEC BCCM",
                            "Bicol State College of Applied Sciences and Technology",
                            "Bicol University",
                            "Biliran Province State University",
                            "Binangonan Catholic College",
                            "BIT International College",
                            "Bohol Island State University (Central Visayas State College of Agriculture)",
                            "Brokenshire College",
                            "Bukidnon State University",
                            "Bulacan Agricultural State College",
                            "Bulacan State University",
                            "Cagayan State University",
                            "Calayan Educational Foundation",
                            "Calayan Educational Foundation",
                            "Camarines Norte State College",
                            "Camarines Sur Polytechnic Colleges",
                            "CAP College Foundation",
                            "Capitol University",
                            "Capiz State University",
                            "Caraga State University",
                            "Carlos Hilado Memorial State College",
                            "Catanduanes State University",
                            "Cavite State University",
                            "Cebu Aeronautical Technical School (Computer Arts and Technological College Legazpi City)",
                            "Cebu Doctors’ University",
                            "Cebu Institute of Medicine",
                            "Cebu Institute of Technology",
                            "Cebu Normal University",
                            "Cebu Technological University",
                            "Center for Industrial Technology and Enterprise",
                            "Central Bicol State University of Agriculture",
                            "Central Colleges of the Philippines",
                            "Central Luzon State University",
                            "Central Mindanao University",
                            "Central Philippine Adventist College",
                            "Central Philippine University",
                            "Centro Escolar University Manila Mendiola",
                            "Chiang Kai Shek College",
                            "City College of Angeles",
                            "Colegio de Dagupan",
                            "Colegio de San Juan de Letran",
                            "Colegio de San Pedro",
                            "Colegio de Sta Catalina de Alejandria",
                            "Colegio San Agustin Bacolod",
                            "College of Development Communication",
                            "College of Technological Sciences Cebu",
                            "College of the Holy Spirit",
                            "Columban College",
                            "Computer Arts and Technology CAT College Polangui",
                            "Comteq Computer and Business College",
                            "Cotabato Foundation College of Science and Technology",
                            "Davao del Norte State College",
                            "Davao del Sur State College",
                            "Davao Doctors College",
                            "Davao Medical School Foundation",
                            "De La Salle Araneta University",
                            "De La Salle College of Saint Benilde",
                            "De La Salle Health Sciences Institute",
                            "De La Salle Lipa",
                            "De La Salle University Dasmariñas",
                            "De La Salle University Manila",
                            "Dipolog Medical Center College Foundation",
                            "Divine Word College of Legazpi",
                            "DMMA College of Southern Philippines",
                            "Don Bosco College",
                            "Don Honorio Ventura State University DHVSU",
                            "Don Honorio Ventura Technological State University",
                            "Don Mariano Marcos Memorial State University",
                            "Dr Aurelio Mendoza Memorial College",
                            "Eastern Samar State University",
                            "Eastern Visayas State University",
                            "Emilio Aguinaldo College",
                            "Eulogio Amang Rodríguez Institute of Science and Technology",
                            "F L Vargas College",
                            "Far Eastern University Cavite",
                            "Far Eastern University East Asia College",
                            "Far Eastern University Institute of Medicine",
                            "Far Eastern University Philippines",
                            "Father Saturnino Urios University",
                            "Fatima University",
                            "Feati University",
                            "Fernandez College of Arts and Technology",
                            "Filamer Christian University",
                            "First Asia Institute of Technology and Humanities",
                            "Foundation University",
                            "Gingoog City Colleges",
                            "Guagua National Colleges Pampanga",
                            "Guimaras State College",
                            "Holy Angel University",
                            "Holy Child Colleges of Butuan",
                            "Holy Cross of Davao College",
                            "Holy Name University",
                            "Holy Trinity University Philippines",
                            "ICCT Colleges",
                            "Ifugao State University",
                            "Iligan Computer Institute",
                            "Iligan Medical Center College",
                            "Ilocos Sur Community College",
                            "Ilocos Sur Polytechnic State College",
                            "Iloilo Doctors’ College",
                            "Iloilo Science and Technology University (Western Visayas College of Science & Technology)",
                            "Informatics Computer Institute",
                            "Information and Communications Technology Academy",
                            "Inspire Sports Academy",
                            "International Graduate School of Leadership (International School of Theology Asia)",
                            "Isabela State University",
                            "Je Mondejar Computer College",
                            "John B Lacson Foundation Maritime University",
                            "Jose Maria College",
                            "Jose Rizal Memorial State University",
                            "Jose Rizal University",
                            "Kalayaan College",
                            "La Consolacion College Bacolod",
                            "La Consolacion University Philippines",
                            "La Patria College",
                            "La Salle University Ozamiz",
                            "Laguna State Polytechnic University",
                            "Leyte Normal University",
                            "Liceo de Cagayan University",
                            "Lipa City Colleges",
                            "Lorma Colleges MacArthur",
                            "Lyceum Northwestern University",
                            "Lyceum of the Philippines University Batangas",
                            "Lyceum of the Philippines University",
                            "Malayan Colleges Laguna",
                            "Manila Business College",
                            "Manila Central University",
                            "Manuel L Quezon University",
                            "Manuel S Enverga University",
                            "Mapua Institute of Technology",
                            "Marian College",
                            "Mariano Marcos State University",
                            "Maritime Academy of Asia and the Pacific Kamaya Point",
                            "Mater Dei College Bohol",
                            "Metro Dumaguete College",
                            "MHAM College of Medicine",
                            "Microcity College of Business and Technology",
                            "Mindanao State University at Naawan",
                            "Mindanao State University General Santos",
                            "Mindanao State University Iligan Institute of Technology",
                            "Mindanao State University Marawi City",
                            "Mindanao State University Tawi-Tawi College of Technology and Oceanography",
                            "Mindanao State University",
                            "Mindoro State University",
                            "Miriam College",
                            "Misamis University",
                            "Mountain Province State Polytechnic College",
                            "Mountain View College Philippines",
                            "MSC Institute of Technology",
                            "Naga College Foundation",
                            "National College of Business and Arts NCBA",
                            "National College of Science and Technology",
                            "National Defense College of the Philippines",
                            "National Teachers College Philippines",
                            "National University Philippines",
                            "Negros College",
                            "Negros Oriental State University (Central Visayas Polytechnic College)",
                            "New Era University",
                            "Northeastern college",
                            "Northern Luzon Adventist College",
                            "Northern Negros State College of Science & Technology",
                            "Northwest Samar State University",
                            "Northwestern University Laoag City",
                            "Norzagaray College",
                            "Notre Dame of Dadiangas University",
                            "Notre Dame of Kidapawan College",
                            "Notre Dame of Marbel University",
                            "Notre Dame University Cotabato",
                            "Nueva Ecija University of Science and Technology",
                            "Nueva Vizcaya State University",
                            "NYK-TDG Maritime Academy",
                            "Occidental Mindoro State College",
                            "Our Lady of the Pillar College Cauayan",
                            "Palawan State University",
                            "Palompon Institute of Technology",
                            "Pampanga State Agricultural University",
                            "Pangasinan State University",
                            "PanPacific University North Philippines",
                            "Panpacific University North Philippines",
                            "Partido State University",
                            "Pasig Catholic College",
                            "PATTS College of Aeronautics",
                            "Philippine Christian University",
                            "Philippine College of Criminology",
                            "Philippine College of Ministry",
                            "Philippine Merchant Marine Academy",
                            "Philippine Military Academy",
                            "Philippine National Police Academy",
                            "Philippine Normal University",
                            "Philippine School of Business Administration",
                            "Philippine Women’s University",
                            "PLT College",
                            "Polytechnic University of the Philippines",
                            "President Ramon Magsaysay State University",
                            "Quirino State University",
                            "Republic Central Colleges",
                            "Riverside College",
                            "Rizal Technological University",
                            "Rogationist College",
                            "Romblon State University",
                            "Sacred Heart College Lucena City",
                            "Saint Ferdinand College",
                            "Saint Francis of Assisi College Cavite",
                            "Saint Joseph College Maasin",
                            "Saint Joseph Institute of Technology",
                            "Saint Jude College",
                            "Saint Louis College",
                            "Saint Louis University Baguio City",
                            "Saint Luke’s College of Medicine",
                            "Saint Mary’s University of Bayombong",
                            "Saint Michael’s College of Laguna",
                            "Saint Paul University Dumaguete",
                            "Saint Paul University Manila",
                            "Saint Paul University Pasig",
                            "Saint Paul University Philippines",
                            "Salazar Colleges of Science and Institute of Technology",
                            "Samar State University",
                            "Samson College of Science and Technology",
                            "San Antonio de Padua College",
                            "San Beda University",
                            "San Carlos College",
                            "San Isidro College",
                            "San Pablo Colleges San Pablo City Laguna",
                            "San Pedro College of Business Administration",
                            "San Sebastian College Manila",
                            "San Sebastian College Recoletos de Cavite",
                            "Siena College of Taytay",
                            "Silliman University",
                            "Siquijor State College",
                            "Sorsogon State College",
                            "Southeast Asia Interdisciplinary Development Institute",
                            "Southern City Colleges",
                            "Southern Leyte State University",
                            "Southern Luzon State University (Polytechnic College)",
                            "Southern Philippines Agri Business and Marine and Aquatic School of Technology",
                            "Southville SISFU",
                            "Southway College of Technology",
                            "Southwestern University Cebu Philippines",
                            "Southwestern University PHINMA",
                            "St Augustine School of Nursing",
                            "St Cecilia’s College Cebu",
                            "St Joseph’s College Quezon City",
                            "St Louis College Valenzuela",
                            "St Marys College",
                            "St Nicolas College of Business and Technology",
                            "St Paul College of Ilocos Sur",
                            "St Paul University Iloilo",
                            "St Paul University Surigao",
                            "St Scholastica’s College",
                            "St Vincent’s College",
                            "St. Paul University Quezon City",
                            "Sultan Kudarat State University",
                            "Surigao del Sur State University",
                            "Surigao State College of Technology",
                            "System Technology Institute",
                            "Systems Plus Computer College Quezon City",
                            "Tanchuling College",
                            "Tarlac Agricultural University",
                            "Tarlac Agricultural University",
                            "Tarlac State University",
                            "Technological Institute of the Philippines",
                            "Technological Research for Advanced Computer Education College",
                            "Technological University of the Philippines",
                            "The Lewis College",
                            "Trinity University of Asia (Trinity College of Quezon City)",
                            "Universidad Aldersgate",
                            "Universidad de Santa Isabel",
                            "Universidad de Zamboanga",
                            "University of Antique (Polytechnic State College of Antique)",
                            "University of Asia and the Pacific",
                            "University of Baguio",
                            "University of Batangas",
                            "University of Bohol",
                            "University of Cagayan Valley",
                            "University of Caloocan City",
                            "University of Cebu",
                            "University of Cebu",
                            "University of Eastern Philippines",
                            "University of Iloilo",
                            "University of La Salette",
                            "University of Luzon",
                            "University of Makati",
                            "University of Manila",
                            "University of Mindanao",
                            "University of Negros Occidental Recoletos",
                            "University of Northeastern Philippines",
                            "University of Northern Philippines",
                            "University of Nueva Caceres",
                            "University of Pangasinan",
                            "University of Perpetual Help System Dalta",
                            "University of Perpetual Help System Laguna",
                            "University of Rizal System",
                            "University of Saint Anthony Iriga City",
                            "University of Saint La Salle Bacolod",
                            "University of Saint Louis Tuguegarao",
                            "University of San Agustin",
                            "University of San Carlos",
                            "University of San Jose Recoletos",
                            "University of Santo Tomas",
                            "University of Science and Technology of Southern Philippines USTP",
                            "University of Southeastern Philippines",
                            "University of Southern Mindanao",
                            "University of Sto Tomas Legazpi Bicol Dominican University",
                            "University of the Assumption",
                            "University of the City of Manila",
                            "University of the Cordilleras (Baguio Colleges Foundation)",
                            "University of the East Ramon Magsaysay",
                            "University of the East",
                            "University of the Immaculate Conception",
                            "University of the Philippines Baguio",
                            "University of the Philippines Cebu",
                            "University of the Philippines Diliman",
                            "University of the Philippines Manila",
                            "University of the Philippines Mindanao",
                            "University of the Philippines Visayas",
                            "University of the Philippines",
                            "University of the Visayas",
                            "Urdaneta City University",
                            "Virgen Milagrosa University Foundation",
                            "Visayas State University",
                            "Wesleyan University Philippines",
                            "West Visayas State University",
                            "Western Institute of Technology",
                            "Western Leyte College of Ormoc City",
                            "Western Mindanao State University",
                            "Western Philippines University",
                            "Xavier University Ateneo de Cagayan",
                            "Zamboanga Peninsula Polytechnic State University",
                            "Zamboanga State College of Marine Sciences and Technology"

]
    school_name_var = tk.StringVar()
    school_name_var.set("Select your school")

    school_name_entry = ttk.Combobox(
        window,
        textvariable=school_name_var,
        values=school_name_options,
        font= ("Montserrat", 12),
        state="readonly",
    )

    school_name_entry.place(
        x=158.0,
        y=242.0,
        width=338.0,
        height=38.0
    )
    
    school_addresses = {
                            "University of the Philippines Diliman": "Diliman, Quezon City",
                            "De La Salle University Manila": "Malate, Manila",
                            "Ateneo de Manila University": "Katipunan Ave, Quezon City",
                            "University of Santo Tomas": "Sampaloc, Manila",
                            "Mindanao State University Iligan Institute of Technology": "Iligan City, Lanao del Norte",
                            "University of San Carlos": "Cebu City",
                            "Mapua Institute of Technology": "Intramuros, Manila",
                            "Visayas State University": "Baybay City, Leyte",
                            "Mindanao State University Marawi City": "Marawi City, Lanao del Sur",
                            "Central Mindanao University": "Musuan, Bukidnon",
                            "Cebu Technological University": "Cebu City",
                            "Central Luzon State University": "Science City of Muñoz, Nueva Ecija",
                            "Far Eastern University Philippines": "Sampaloc, Manila",
                            "University of the Philippines": "Ermita, Manila",
                            "Batangas State University": "Batangas City, Batangas",
                            "University of Southern Mindanao": "Kabacan, Cotabato",
                            "West Visayas State University": "La Paz, Iloilo City",
                            "Silliman University": "Dumaguete City, Negros Oriental",
                            "University of the Philippines Visayas": "Iloilo City, Iloilo",
                            "Polytechnic University of the Philippines": "Sta. Mesa, Manila",
                            "Centro Escolar University Manila Mendiola": "San Miguel, Manila",
                            "Adamson University": "Ermita, Manila",
                            "Technological University of the Philippines": "Ermita, Manila",
                            "University of the East": "Sampaloc, Manila",
                            "National University Philippines": "Sampaloc, Manila",
                            "Ateneo de Davao University": "Davao City",
                            "University of Science and Technology of Southern Philippines USTP": "Cagayan de Oro City",
                            "Pangasinan State University": "Lingayen, Pangasinan",
                            "University of San Jose Recoletos": "Cebu City",
                            "Western Mindanao State University": "Zamboanga City",
                            "Isabela State University": "Cauayan City, Isabela",
                            "Asian Institute of Management": "Makati City",
                            "Cavite State University": "Indang, Cavite",
                            "Jose Rizal University": "Mandaluyong City",
                            "Holy Angel University": "Angeles City, Pampanga",
                            "Fatima University": "Valenzuela City",
                            "Angeles University Foundation": "Angeles City, Pampanga",
                            "University of the Philippines Mindanao": "Mintal, Davao City",
                            "Benguet State University": "La Trinidad, Benguet",
                            "Bulacan State University": "Malolos City, Bulacan",
                            "Saint Louis University Baguio City": "Baguio City",
                            "Caraga State University": "Butuan City",
                            "Lyceum of the Philippines University": "Intramuros, Manila",
                            "Cebu Normal University": "Cebu City",
                            "Nueva Ecija University of Science and Technology": "Cabanatuan City, Nueva Ecija",
                            "Xavier University Ateneo de Cagayan": "Cagayan de Oro City",
                            "Asia Pacific College": "Makati City",
                            "Cagayan State University": "Tuguegarao City, Cagayan",
                            "University of the Philippines Cebu": "Cebu City",
                            "Emilio Aguinaldo College": "Ermita, Manila",
                            "Don Mariano Marcos Memorial State University": "San Fernando City, La Union",
                            "University of Mindanao": "Davao City",
                            "Saint Mary’s University of Bayombong": "Bayombong, Nueva Vizcaya",
                            "Adventist University of the Philippines": "Silang, Cavite",
                            "Cebu Institute of Technology": "Cebu City",
                            "Samar State University": "Catbalogan City, Samar",
                            "Bicol University": "Legazpi City, Albay",
                            "Mariano Marcos State University": "Batac City, Ilocos Norte",
                            "University of Asia and the Pacific": "Pasig City",
                            "Bataan Peninsula State University": "Balanga City, Bataan",
                            "University of the Philippines Baguio": "Baguio City",
                            "Manila Central University": "Caloocan City",
                            "Mindanao State University General Santos": "General Santos City",
                            "University of Southeastern Philippines": "Davao City",
                            "Philippine Normal University": "Manila City",
                            "Ateneo de Zamboanga University": "Zamboanga City",
                            "San Beda University": "Mendiola, Manila",
                            "Leyte Normal University": "Tacloban City, Leyte",
                            "University of the Philippines Manila": "Ermita, Manila",
                            "Lyceum of the Philippines University Batangas": "Batangas City, Batangas",
                            "Central Philippine University": "Jaro, Iloilo City",
                            "Tarlac State University":"Tarlac City, Tarlac",
                            "Far Eastern University East Asia College": "Sampaloc, Manila",
                            "University of the Cordilleras (Baguio Colleges Foundation)": "Baguio City",
                            "Universidad de Zamboanga": "Zamboanga City",
                            "Occidental Mindoro State College": "San Jose, Occidental Mindoro",
                            "Malayan Colleges Laguna": "Cabuyao, Laguna",
                            "Eastern Visayas State University": "Tacloban City, Leyte",
                            "Sacred Heart College Lucena City": "Lucena City, Quezon",
                            "System Technology Institute": "Cubao, Quezon City",
                            "Technological Institute of the Philippines": "Cubao, Quezon City",
                            "De La Salle University Dasmariñas": "Dasmariñas City, Cavite",
                            "De La Salle Health Sciences Institute": "Dasmariñas City, Cavite",
                            "Far Eastern University Institute of Medicine": "Sampaloc, Manila",
                            "University of the Immaculate Conception": "Davao City",
                            "Adventist International Institute of Advanced Studies": "Silang, Cavite",
                            "Arellano University": "Sampaloc, Manila",
                            "University of Batangas": "Batangas City, Batangas",
                            "University of San Agustin": "Iloilo City",
                            "Southern Luzon State University (Polytechnic College)": "Lucban, Quezon",
                            "De La Salle Lipa": "Lipa City, Batangas",
                            "Rizal Technological University": "Mandaluyong City",
                            "MSC Institute of Technology": "Cainta, Rizal",
                            "Aklan State University": "Banga, Aklan",
                            "Philippine Christian University": "Manila City",
                            "De La Salle College of Saint Benilde": "Malate, Manila",
                            "University of Bohol": "Tagbilaran City, Bohol",
                            "Miriam College": "Quezon City",
                            "De La Salle Araneta University:": "Malabon City",
                            "University of Eastern Philippines:": "Catarman, Northern Samar",
                            "San Sebastian College Recoletos de Cavite": "Cavite City, Cavite",
                            "University of Perpetual Help System Dalta": "Las Piñas City",
                            "St Scholastica’s College": "Malate, Manila",
                            "Bicol Christian College of Medicine AMEC BCCM": "Legazpi City, Albay",
                            "Romblon State University": "Odiongan, Romblon",
                            "University of Saint Louis Tuguegarao": "Tuguegarao City, Cagayan",
                            "University of the City of Manila": "Intramuros, Manila",
                            "University of Baguio": "Baguio City",
                            "University of Saint La Salle Bacolod": "Bacolod City, Negros Occidental",
                            "Southern Leyte State University": "Sogod, Southern Leyte",

    }
    # school_addresses = {
    #     "Ateneo de Manila University": "Katipunan Ave, Quezon City",
    #     "Far Eastern University": "Sampaloc, Manila",
    #     "Polytechnic University of the Philippines": "Sta. Mesa, Manila",
    #     "Polytechnic University of the Philippines-San Juan": "San Juan, Metro Manila",
    #     "Polytechnic University of the Philippines-Parañaque": "Parañaque, Metro Manila",
    #     "Polytechnic University of the Philippines-Taguig": "Taguig, Metro Manila",
    #     "Philippines Science High School": "Agham Rd, Diliman, Quezon City",
    #     "University of the East": "Sampaloc, Manila",
    #     "Japan-Philippines Institute of Technology-Plaridel": "Plaridel, Bulacan",
    #     "Technological Institute of the Philippines": "Manila, Metro Manila",
    #     "Technological University of the Philippines": "Ermita, Manila",
    #     "University of the Philippines-Diliman": "Diliman, Quezon City",
    #     "University of the Philippines-Los Baños": "Los Baños, Laguna",
    # }

    # Provide me a list of college Universities in the Philippines

    school_address_entry = tk.Entry(
        bd=0,
        font=("Montserrat", 12),
        bg="#FFFFFF",
        highlightthickness=0
    )
    school_address_entry.place(
        x=528.0,
        y=241.0,
        width=336.0,
        height=38.0
    )
    # Bind the ComboboxSelected event to the update_school_address function
    school_name_entry.bind("<<ComboboxSelected>>", update_school_address)


    
    # Education Attainment
    education_attainment_options = ["Junior High School", "Senior High School", "College"]
    education_attainment_var = tk.StringVar()
    education_attainment_var.set("Select Education Attainment")

    education_attainment_entry = ttk.Combobox(
        window,
        textvariable=education_attainment_var,
        values=education_attainment_options,
        font=fontstyle,
        state="readonly",
    )

    education_attainment_entry.place(
        x=528.0,
        y=328.0,
        width=336.0,
        height=38.0
    )

    
    
    # Date Graduated
    date_graduated_entry = DateEntry(
        window,
        font=fontstyle,
        background="#FFFFFF",
        foreground="#000716",
        borderwidth=2,  # Set the borderwidth to 0 to remove the border
        selectbackground="#359ca6",  # Customize the background color when the date is selected
        selectforeground="white",  # Customize the foreground color when the date is selected
        normalbackground="#FFFFFF",  # Customize the background color when the widget is not focused
        normalforeground="#000716",  # Customize the foreground color when the widget is not focused
        highlightthickness=0,
        arrowcolor="#FFFFFF",
        date_pattern="yyyy-mm-dd",  # Customize the date pattern to your preference
        firstweekday = "sunday"
    )
    date_graduated_entry.place(
        x=159.0,
        y=328.0,
        width=336.0,
        height=38.0
    )

    
    # --------------------------------------------------------------------------------#
    # ----------------------------------- BUTTONS ----------------------------------- #
    # --------------------------------------------------------------------------------#
    
    # Add More Button
    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=add_more_clicked,
        relief="flat"
    )
    button_1.place(
        x=404.0,
        y=449.0,
        width=216.0,
        height=33.0
    )

    # Back Button
    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=back_clicked,
        relief="flat"
    )
    button_2.place(
        x=151.0,
        y=509.0,
        width=178.0,
        height=33.0
    )

    # Next Button
    button_image_3 = PhotoImage(
        file=relative_to_assets("button_3.png"))
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=next_clicked,
        relief="flat"
    )
    button_3.place(
        x=694.0,
        y=509.0,
        width=178.0,
        height=33.0
    )
    display_values()
    window.resizable(False, False)
    window.mainloop()


if __name__ == "__main__":
    education_main()
    